src/AppBundle/Entity/Address.php
<?php

namespace AppBundle\Entity;

/**
 * Address
 */
class Address
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var boolean
     */
    private $default = 0;

    /**
     * @var \DateTime
     */
    private $created_at;

    /**
     * @var \DateTime
     */
    private $updated_at;

    /**
     * @var \AppBundle\Entity\AddressData
     */
    private $addr;

    /**
     * @var \AppBundle\Entity\Customer
     */
    private $customer;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set default
     *
     * @param boolean $default
     *
     * @return Address
     */
    public function setDefault($default)
    {
        $this->default = $default;

        return $this;
    }

    /**
     * Get default
     *
     * @return boolean
     */
    public function getDefault()
    {
        return $this->default;
    }
    
    /**
     * Is default
     *
     * @return boolean
     */
    public function isDefault()
    {
        return (boolean) $this->default;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Address
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Address
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set addr
     *
     * @param \AppBundle\Entity\AddressData $addr
     *
     * @return Address
     */
    public function setAddr(\AppBundle\Entity\AddressData $addr)
    {
        $this->addr = $addr;

        return $this;
    }

    /**
     * Get addr
     *
     * @return \AppBundle\Entity\AddressData
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * Set customer
     *
     * @param \AppBundle\Entity\Customer $customer
     *
     * @return Address
     */
    public function setCustomer(\AppBundle\Entity\Customer $customer)
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Get customer
     *
     * @return \AppBundle\Entity\Customer
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    public function prePersist()
    {
        $this->setCreatedAt(new \DateTime());
        $this->setUpdatedAt(new \DateTime());
    }

    public function preUpdate()
    {
        $this->setUpdatedAt(new \DateTime());
    }
    
    public function __toString() {
        return trim($this->getStreet()." ".$this->getCity()." ".$this->getState()." ".$this->getCode());
    }
    
    // Get Addr fields
    public function getStreet()
    {
        return $this->getAddr()->getStreet();
    }
    public function getCity()
    {
        return $this->getAddr()->getCity();
    }
    public function getState()
    {
        return $this->getAddr()->getState();
    }
    public function getCode()
    {
        return $this->getAddr()->getCode();
    }
}

src/AppBundle/Entity/Bill.php
<?php /** @noinspection PhpUnused */

namespace AppBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * Bill
 */
abstract class Bill
{
    /**
     * @var integer
     */
    protected $id;
   
    /**
     * @var integer
     */
    protected $sequence;

    /**
     * @var string
     */
    protected $number;

    /**
     * @var string
     */
    protected $paid = 0;
    
    /**
     * @var float
     */
    protected $total;

    /**
     * @var DateTime
     */
    protected $date;

    /**
     * @var Customer
     */
    protected $customer;

    /**
     * @var CustomerData
     */
    protected $customer_data;

    /**
     * @var Address
     */
    protected $address;

    /**
     * @var AddressData
     */
    protected $address_data;

    /**
     * @var Company
     */
    protected $company;

    /**
     * @var DateTime
     */
    protected $created_at;

    /**
     * @var DateTime
     */
    protected $updated_at;

    /**
     * @var Collection
     */
    protected $items;


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->date = new DateTime();
        $this->items = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set sequence
     *
     * @param integer $sequence
     *
     * @return Bill
     */
    public function setSequence($sequence)
    {
        $this->sequence = $sequence;
        $prefix = $this->getCompany()->getPrefixInvoice();
        $this->setNumber($prefix.date('y').str_pad($sequence, 5, "00000", STR_PAD_LEFT));

        return $this;
    }

    /**
     * Get sequence
     *
     * @return integer
     */
    public function getSecuence()
    {
        return $this->sequence;
    }

    /**
     * Set number
     *
     * @param string $number
     *
     * @return Bill
     */
    public function setNumber($number)
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Get number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Set paid
     *
     * @param string $paid
     *
     * @return Bill
     */
    public function setPaid($paid)
    {
        $this->paid = $paid;

        return $this;
    }

    /**
     * Get paid
     *
     * @return string
     */
    public function getPaid()
    {
        return $this->paid;
    }

    /**
     * Set is paid
     *
     * @param boolean $paid
     *
     * @return Bill
     */
    public function setIsPaid($paid)
    {
        if ($paid){
            $this->setPaid($this->getTotal());
        }

        return $this;
    }

    /**
     * Get is paid
     *
     * @return bool
     */
    public function getIsPaid()
    {
        return abs($this->getPaid()) >= abs($this->getTotal());
    }
    public function isPaid()
    {
        return $this->getIsPaid();
    }

    /**
     * Set date
     *
     * @param DateTime $date
     *
     * @return Bill
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set customer
     *
     * @param Customer $customer
     *
     * @return Bill
     */
    public function setCustomer(Customer $customer)
    {
        $this->customer = $customer;
        if (!$this->getAddress() && $customer->getAddressDefault()){
            $this->setAddress($customer->getAddressDefault());
        }

        return $this;
    }

    /**
     * Get customer
     *
     * @return Customer
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * Set customer
     *
     * @param CustomerData $customerData
     *
     * @return Bill
     */
    public function setCustomerData(CustomerData $customerData)
    {
        $this->customer_data = $customerData;

        return $this;
    }

    /**
     * Get customer
     *
     * @return CustomerData
     */
    public function getCustomerData()
    {
        return $this->customer_data;
    }

    /**
     * Set address
     *
     * @param Address $address
     *
     * @return Bill
     */
    public function setAddress(Address $address = null)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return Address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set address
     *
     * @param AddressData $addressData
     *
     * @return Bill
     */
    public function setAddressData(AddressData $addressData)
    {
        $this->address_data = $addressData;

        return $this;
    }

    /**
     * Get address
     *
     * @return AddressData
     */
    public function getAddressData()
    {
        return $this->address_data;
    }

    /**
     * Set company
     *
     * @param Company $company
     * @return Bill
     */
    public function setCompany(Company $company)
    {
        $this->company = $company;
        
        return $this;
    }

    /**
     * Get company
     *
     * @return Company
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Set createdAt
     *
     * @param DateTime $createdAt
     *
     * @return Bill
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updatedAt
     *
     * @param DateTime $updatedAt
     *
     * @return Bill
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Add item
     *
     * @param InvoiceItem $item
     *
     * @return Bill
     */
    public function addItem(InvoiceItem $item)
    {
        $this->items[] = $item;
        $item->setInvoice($this);
        
        return $this;
    }

    /**
     * Remove item
     *
     * @param InvoiceItem $item
     */
    public function removeItem(InvoiceItem $item)
    {
        $this->items->removeElement($item);
    }

    /**
     * Get items
     *
     * @return Collection
     */
    public function getItems()
    {
        return $this->items;
    }

    public function prePersist()
    {
        $this->setCreatedAt(new DateTime());
        $this->setUpdatedAt(new DateTime());
        $this->total = $this->getTotal();
    }

    public function preUpdate()
    {
        $this->setUpdatedAt(new DateTime());
        $this->total = $this->getTotal();
    }

    public function __toString()
    {
        return (string) $this->getNumber();
    }

    /**
     * Alias get customer identifier for sonata (embedded not working)
     * 
     * @return string
     */
    public function getIdentifier()
    {
        return $this->getCustomerData()->getIdentifier();
    }

    /**
     * Alias get customer fullname for sonata (embedded not working)
     * 
     * @return string
     */
    public function getFullname()
    {
        return $this->getCustomerData()->getFullname();
    }

   /**
     * Get Total with discount and without tax (euros) only parts
     * 
     * @return float
     */
    public function getBaseParts()
    {
        $base = 0;
        foreach ($this->getItems() as $item){
            if ($item->getItem() instanceof Part){
                $base += $item->getBase();
            }
        }

        return round($base, 2);
    }

    /**
     * Get Total with discount and without tax (euros) only labors
     * 
     * @return float
     */
    public function getBaseLabors()
    {
        $base = 0;
        foreach ($this->getItems() as $item){
            if ($item->getItem() instanceof Labor){
                $base += $item->getBase();
            }
        }

        return round($base, 2);
    }
    
    /**
     * Get Total with discount and without tax (euros)
     * 
     * @return float
     */
    public function getBase()
    {
        $base = 0;
        foreach ($this->getItems() as $item){
            $base += $item->getBase();
        }

        return round($base, 2);
    }

    /**
     * Get Tax value of price with discount applied (euros) 
     * 
     * @return float
     */
    public function getTax()
    {
        $tax = 0;
        foreach ($this->getItems() as $item){
            $tax += $item->getTaxValue();
        }

        return round($tax, 2);
    }

    /**
     * Get Tax value of price with discount applied (euros) 
     * 
     * @return float
     */
    public function getTotal()
    {
        $total = $this->getBase()+$this->getTax();
        
        return round($total, 2);
    }

    /**
     * @return string|null
     */
    public function getType()
    {
        if ($this instanceof Invoice){
            return 'Factura';
        }elseif ($this instanceof InvoiceCash){
            return 'Factura Contado';
        }elseif ($this instanceof InvoiceRefund){
            return 'Abono Factura';
        }elseif ($this instanceof InvoiceCashRefund){
            return 'Abono Factura Contado';
        }

        return null;
    }
}

src/AppBundle/Entity/Labor.php
<?php

namespace AppBundle\Entity;

use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Labor
 */
class Labor extends Item
{

    /**
     * @var \AppBundle\Entity\LaborType
     */
    private $type;

    /**
     * @var string
     */
    private $unit;

    /**
     * No save in database, only for calculate unit
     * 
     * @var string
     */
    private $price;

    /**
     * No save in database, only for calculate unit
     * 
     * @var string
     */
    private $hour;

    /**
     * Set type
     *
     * @param \AppBundle\Entity\LaborType $type
     *
     * @return Labor
     */
    public function setType(\AppBundle\Entity\LaborType $type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return \AppBundle\Entity\LaborType
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set unit
     *
     * @param string $unit
     *
     * @return Labor
     */
    public function setUnit($unit)
    {
        $this->unit = $unit;

        return $this;
    }

    /**
     * Get unit
     *
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }
    
    /**
     * Set price
     *
     * @param string $price
     *
     * @return Labor
     */
    public function setPrice($price)
    {
        if ($price){
            $this->setValue($price);
            $this->unit = 'EUR';
        }

        $this->price = $price;
        
        return $this;
    }

    /**
     * Get price
     *
     * @return string
     */
    public function getPrice()
    {
        if ($this->unit == 'EUR'){
            return $this->getValue();
        }else{
            return 0;
        }
    }

    /**
     * Set hour
     *
     * @param string $hour
     *
     * @return Labor
     */
    public function setHour($hour)
    {
        if ($hour){
            $this->setValue($hour);
            $this->unit = 'HOUR';
        }

        $this->hour = $hour;
        
        return $this;
    }

    /**
     * Get hour
     *
     * @return string
     */
    public function getHour()
    {
        if ($this->unit == 'HOUR'){
            return $this->getValue();
        }else{
            return 0;
        }
    }


    public function validate(ExecutionContextInterface $context)
    {
        // check if the name is actually a fake name
        if ($this->hour && $this->price) {
            $context->buildViolation('No puede definir precio y horas a la vez.')
                ->atPath('price')
                ->addViolation();
        }
    }

    /**
     * Get Amount (Amount is default 1)
     * @return int
     */
    public function getAmount()
    {
        if ($this->unit == "HOUR"){
            return $this->getValue();
        }else{
            return 1;
        }
    }
}

src/AppBundle/Resources/views/Admin/listActionAddInvoiceRefund.html.twig
<a href="{{ path('admin_app_invoicerefund_create') }}?cod={{ object.id}}" class="btn btn-sm btn-default view_link" title="Abono">
    <i class="glyphicon glyphicon-plus"></i>
    Abono
</a>

src/AppBundle/Resources/views/Admin/listActionAddOrderEntry.html.twig
<a href="{{ path('admin_app_orderentry_create') }}?{{cod}}={{ object.id}}" class="btn btn-sm btn-default view_link" title="Orden Entrada">
    <i class="glyphicon glyphicon-plus"></i>
    Orden Entrada
</a>

src/AppBundle/Resources/views/Admin/listActionAddVehicle.html.twig
<a href="{{ path('admin_app_vehicle_create') }}?cod={{ object.id}}" class="btn btn-sm btn-default view_link" title="Nuevo vehiculo">
    <i class="glyphicon glyphicon-plus"></i>
    Nuevo vehiculo
</a>

src/AppBundle/Resources/views/Admin/listActionCustomer.html.twig
{% include 'AppBundle:Admin:listActionAddVehicle.html.twig' %}
{% include 'AppBundle:Admin:listActionAddOrderEntry.html.twig' with {'cod': 'cod_c'} %}

src/AppBundle/Resources/views/Admin/listActionInvoiceReceipt.html.twig
{% include 'AppBundle:Admin:listActionPrintInvoiceReceipt.html.twig' %}

src/AppBundle/Resources/views/Admin/listActionPrintInvoiceCashRefund.html.twig
<a href="{{ path('admin_print_cash_refund', {'refund': object.id}) }}" target="_blank" class="btn btn-sm btn-default view_link" title="Imprimir">
    <i class="glyphicon glyphicon-print"></i>
    Imprimir
</a>

src/AppBundle/Resources/views/Admin/listActionViewVehicleRecord.html.twig
<a href="{{ path('admin_app_vehiclerecord_list') }}?filter%5Bregistration%5D%5Bvalue%5D={{ object.registration }}&filter%5B_page%5D=1&filter%5B_sort_by%5D=id&filter%5B_sort_order%5D=DESC&filter%5B_per_page%5D=32" class="btn btn-sm btn-default show_link" title="Historial">
 <i class="fa fa-search-plus"></i>
 Historial
</a> 

src/AppBundle/Resources/views/Admin/printInvoiceCash.html.twig
<!DOCTYPE html>
<html class="">
    <head>
        {% block meta_tags %}
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta charset="UTF-8">
            <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        {% endblock %}

        {% block stylesheets %}
             <link rel="stylesheet" href="{{ asset('/bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css') }}">
             <link rel="stylesheet" href="{{ asset('/bundles/app/css/custom.css') }}">
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body onload="window.print()">
        <div class="fact-box">
                <table>
                    <tr>
                        <td width="100px"><img class="fact-logo" src="{{ asset(sonata_admin.adminPool.titlelogo) }}" alt="{{ invoice.company.name }}"></td>                              
                        <td><h2 class="fact-title">{{ invoice.company.name }}<h2></td>
                    </tr>
                </table>
                <h6 class="text-center">
                    <small>
                        {{ invoice.company.addr.street }} {{ invoice.company.addr.code }} {{ invoice.company.addr.city }} ({{ invoice.company.addr.state }})
                        <br>
                        <label>CIF:</label><span>{{ invoice.company.identifier }}</span>
                        <label>Tel.:</label><span>{{ invoice.company.phone }}</span>
                        <label>Reg. Esp:</label><span>{{ invoice.company.registry }}</span>
                    </small>
                </h6>
                <table width="100%">
                    <tr>
                        <td width="45%">
                            <div class="col-xs-12 col-md-12 col-lg-12 pull-left">
                                <div class="panel panel-default height">
                                    <div class="panel-body small">
                                        <table width="100%" height="130px">
                                            <tr><td><label>FATCURA:</label></td><td align="right"><span>{{ invoice.number }}</span></td></tr>
                                            <tr><td><label>Fecha:</label></td><td align="right"><span>{{ invoice.date | date('d/m/Y') }}</span></td></tr>
                                            <tr><td><label>Nº Cliente:</label></td><td align="right"><span>{{ invoice.customer.id }}</span></td></tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td width="55%">
                            <div class="col-xs-12 col-md-12 col-lg-12 pull-left">
                                <div class="panel panel-default height">
                                    <div class="panel-body small">
                                        <table width="100%" height="130px">
                                            <tr><td width="40%"><label>Nombre:</label></td><td><span>{{ invoice.customerData.fullname }}</span></td></tr>
                                            <tr><td><label>Dirección:</label></td><td><span>{% if invoice.addressData is defined %}{{ invoice.addressData.street }}{% endif %}</span></td></tr>
                                            <tr><td><label>Código postal:</label></td><td><span>{% if invoice.addressData is defined %}{{ invoice.addressData.code }}{% endif %}</span></td></tr>
                                            <tr><td><label>NIF:</label></td><td><span>{{ invoice.customerData.identifier }}</span></td></tr>
                                            <tr><td><label>Teléfono:</label></td><td><span>{{ invoice.customerData.phone }} {{ invoice.customerData.movil }}</span></td></tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <div class="col-xs-12 col-md-12 col-lg-12 pull-left">
                    <div class="panel panel-default height">
                        <div class="panel-body small">
                            <table width="100%" class="small">
                                <tr>
                                    <td><label>Matricula:</label><span></span></td>
                                    <td><label>Bastidor:</label><span></span></td>
                                    <td><label>Vehículo:</label><span></span></td>
                                    <td><label>Kms.:</label><span></span></td>
                                    <td><label>Depósito:</label><span></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12 col-lg-12 pull-left">
{#                <p><strong>Mano de Obra:</strong></p>#}
                </div>
                <div class="col-xs-12 col-md-12 col-lg-12 pull-left small fact-invoice-container">
                    <p><strong>Mano de Obra:</strong></p>
                    <table>
                        <tr>
                            <td width="10%">Cant. / Horas</td>
                            <td width="30%">Descripción</td>
                            <td width="20%" align="right">Precio</td>
                            <td width="20%" align="right">Descuento</td>
                            <td width="20%" align="right">Total</td>
                        </tr>
                    {% for item in invoice.items if is_labor(item.item) %}
                        <tr>
                            <td>{{ item.amount }}</td>
                            <td>{{ item.description }}</td>
                            <td align="right">{{ item.price|number_format(2, ',', '.') }} €</td>
                            <td align="right">({{ item.discount * 100}}%) {{ item.discountValue|number_format(2, ',', '.') }} €</td>
                            <td align="right">{{ item.base|number_format(2, ',', '.') }} €</td>
                        </tr>
                    {% endfor %}
                        <tr></tr>
                        <tr>
                            <td colspan="4" align="right">Total operaciones:</td>
                            <td align="right">{{ invoice.baseLabors|number_format(2, ',', '.')}} €</td>
                        <tr>
                    </table>
                    <br>
                    <p><strong>Repuestos:</strong></p>
                    <table>
                        <tr>
                            <td width="10%">Cant.</td>
                            <td width="30%">Descripción</td>
                            <td width="20%" align="right">Precio</td>
                            <td width="20%" align="right">Descuento</td>
                            <td width="20%" align="right">Total</td>
                        </tr>
                    {% for item in invoice.items if is_part(item.item) %}
                        <tr>
                            <td>{{ item.amount }}</td>
                            <td>{{ item.description }}</td>
                            <td align="right">{{ item.price|number_format(2, ',', '.') }} €</td>
                            <td align="right">({{ item.discount * 100}}%) {{ item.discountValue|number_format(2, ',', '.') }} €</td>
                            <td align="right">{{ item.base|number_format(2, ',', '.') }} €</td>
                        </tr>
                    {% endfor %}
                        <tr></tr>
                        <tr>
                            <td colspan="4" align="right">Total operaciones:</td>
                            <td align="right">{{ invoice.baseParts|number_format(2, ',', '.')}} €</td>
                        <tr>
                    </table>
                </div>
                <table>
                    <tr>
                        <td width="20%" height="50px">
                            <div class="col-xs-12 col-md-12 col-lg-12 pull-left">
                                <div class="panel panel-default height">
                                    <div class="panel-body">
                                        <h6><small>Las piezas cambiadas durante la reparación, excepto las sustituidas en la garantía, están a disposición del cliente al concluir los trabajos, de no ser retiradas en ese momento se entenderá que renuncia a las mismas.</small></h6>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td width="50%">
                            <div class="col-xs-12 col-md-12 col-lg-12 pull-left">
                                <div class="panel panel-default height">
                                    <div class="panel-body">
                                        <h6><small>Esta reparación queda garantizada por tres meses o 2.000 Kms. (15 días o 2.000 Kms. para vehículos industriales), desde la fecha de entrega del vehículo, de acuerdo con las condiciones establecidas por la normativa aplicable. La garantía se entiende que es total, incluyendo mano de obra y piezas sustituidas. Esta garantía puede quedar invalidada por la manipulación por terceros ajenos a la empresa de las piezas garantizadas. Averiado el automóvil en garantía a más de 25 Kms. del taller garante, deberá el cliente ponerse en contacto con éste para que proceda al cumplimiento de la garantía directamente o a traves de tercero. A tales efectos, el aviso se realizará mediante cualquier medio que permita tener constancia de su recepción por el taller reparador.</small></h6>
                                    </div>
                                </div>
                            </div>
                        </td>
                       <td>
                            <div class="col-xs-12 col-md-12 col-lg-12 pull-left">
                                <div class="panel panel-default height">
                                    <div class="panel-body">
                                        <div class="fact-invoice-total">
                                            <table height="100%">
                                                <tr>
                                                    <td>Base:</td>
                                                    <td align="right">{{ invoice.base|number_format(2, ',', '.') }}€</td>
                                                </tr>
                                                <tr>
                                                    <td>%IVA:</td>
                                                    <td align="right">21%</td> 
                                                </tr>
                                                <tr>
                                                    <td>IVA:</td>
                                                    <td align="right">{{ invoice.tax|number_format(2, ',', '.') }}€</td> 
                                                </tr>
                                                <tr>
                                                    <td><h4>Total:</h4></td>
                                                    <td align="right"><h4>{{ invoice.total|number_format(2, ',', '.') }}€</h4></td>
                                                </tr>
                                                {% if invoice.excess is defined and invoice.excess > 0 %}
                                                <tr>
                                                    <td>Franquicia:</td>
                                                    <td align="right">{{ invoice.excess }}</td>
                                                </tr>
                                                <tr>
                                                    <td><h4>Resto:</h4></td>
                                                    <td align="right"><h4>{{ invoice.total|number_format(2, ',', '.') }}€</h4></td>
                                                </tr>
                                                {% endif %}
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <h6 class="text-center">{{ invoice.company.registered }}</h6>
        </div>
    </body>
</html>

src/AppBundle/Resources/views/Admin/showActionBudget.html.twig
<tr>
    <td colspan="2">
        {% include 'AppBundle:Admin:listActionBudget.html.twig' %}
    </td>
</tr>

src/AppBundle/Resources/views/Admin/showActionInvoice.html.twig
<tr>
    <td colspan="2">
        {% include 'AppBundle:Admin:listActionInvoice.html.twig' %}
     </td>
</tr>

src/AppBundle/Resources/views/Admin/showActionInvoiceCash.html.twig
<tr>
    <td colspan="2">
        {% include 'AppBundle:Admin:listActionInvoiceCash.html.twig' %}
     </td>
</tr>

src/AppBundle/Resources/views/Admin/showActionInvoiceCashRefund.html.twig
<tr>
    <td colspan="2">
        {% include 'AppBundle:Admin:listActionInvoiceCashRefund.html.twig' %}
     </td>
</tr>